---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  rubocop-vaporyhumo: config.yml

AllCops:
  NewCops: enable

Bundler/GemVersion:
  Enabled: true
  EnforcedStyle: forbidden

Gemspec/DependencyVersion:
  Enabled: true
  EnforcedStyle: required

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/NumberConversion:
  Enabled: true

Metrics/AbcSize:
  Max: 15

Metrics/BlockLength:
  Max: 5

Metrics/BlockNesting:
  Max: 1

Metrics/ClassLength:
  Max: 50
  CountAsOne: [heredoc]

Metrics/CyclomaticComplexity:
  Max: 5

Metrics/MethodLength:
  Max: 5
  CountAsOne: [heredoc]

Metrics/ModuleLength:
  Max: 50
  CountAsOne: [heredoc]

Metrics/ParameterLists:
  Max: 3

Metrics/PerceivedComplexity:
  Max: 5

Naming/InclusiveLanguage:
  Enabled: true

Performance/Casecmp:
  Enabled: true

Performance/IoReadlines:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

Performance/SelectMap:
  Enabled: true

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/AlignRightLetBrace:
  Enabled: true

RSpec/Pending:
  Enabled: true

Style/ColonMethodCall:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

